import Link from 'next/link';
import { DOCS_LINKS, DOCS_SITE } from '@/config/site';

const ENDPOINTS = [
  { method: 'POST', path: '/v1/memory', role: 'Developer+', notes: 'Write a memory entry' },
  { method: 'POST', path: '/v1/memory/batch', role: 'Developer+', notes: 'Write multiple memories' },
  { method: 'POST', path: '/v1/memory/search', role: 'ReadOnly+', notes: 'Hybrid memory search' },
  { method: 'GET', path: '/v1/memory/:id', role: 'ReadOnly+', notes: 'Fetch a memory by id' },
  { method: 'PUT', path: '/v1/memory/:id', role: 'Developer+', notes: 'Update a memory' },
  { method: 'DELETE', path: '/v1/memory/:id', role: 'Developer+', notes: 'Soft delete a memory' },
  { method: 'POST', path: '/v1/memory/:id/restore', role: 'Developer+', notes: 'Restore soft-deleted memory' },
  { method: 'POST', path: '/v1/memory/export', role: 'ReadOnly+', notes: 'Export memories' },
  { method: 'POST', path: '/v1/memory/import', role: 'Developer+', notes: 'Import memories' },
];

export default function ApiPage() {
  return (
    <>
      <section className="docHeader">
        <h1>API Reference</h1>
        <p>
          Canonical REST surface for Knol OSS gateway plus enterprise tenant OpenAPI links.
        </p>
      </section>

      <section className="section">
        <h2>Configured Service Endpoints</h2>
        <div className="grid">
          <div className="card">
            <h3>Gateway API</h3>
            <p>
              Base URL: <code>{DOCS_SITE.apiBaseUrl}</code>
            </p>
            <p>
              Write/search paths are relative to this base.
            </p>
          </div>
          <div className="card">
            <h3>Tenant Swagger UI</h3>
            <p>
              URL: <code>{DOCS_SITE.tenantSwaggerUrl}</code>
            </p>
            <p>
              OpenAPI docs generated by the tenant service.
            </p>
          </div>
          <div className="card">
            <h3>Config Source</h3>
            <p>
              All docs URLs are configured in <code>frontend/docs/src/config/site.ts</code>.
            </p>
            <p>
              Override via env vars: <code>NEXT_PUBLIC_API_BASE_URL</code> and{' '}
              <code>NEXT_PUBLIC_TENANT_SWAGGER_URL</code>.
            </p>
          </div>
        </div>
      </section>

      <section className="section">
        <h2>Authentication</h2>
        <div className="card">
          <p>Send API key in Authorization header as bearer token:</p>
          <pre>{`Authorization: Bearer knol_live_...`}</pre>
          <p>
            API keys map to tenant + role (`ReadOnly`, `Developer`, `Admin`), and every request is
            tenant-scoped.
          </p>
        </div>
      </section>

      <section className="section">
        <h2>Gateway Endpoints</h2>
        <div className="tableWrap">
          <table>
            <thead>
              <tr>
                <th>Method</th>
                <th>Path</th>
                <th>Role</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              {ENDPOINTS.map((ep) => (
                <tr key={`${ep.method}-${ep.path}`}>
                  <td>
                    <code>{ep.method}</code>
                  </td>
                  <td>
                    <code>{ep.path}</code>
                  </td>
                  <td>{ep.role}</td>
                  <td>{ep.notes}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="section">
        <h2>Write Memory Example</h2>
        <div className="card">
          <pre>{`curl -X POST ${DOCS_SITE.apiBaseUrl}/v1/memory \\
  -H "Authorization: Bearer $KNOL_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{"content":"User likes concise replies","role":"user"}'`}</pre>
          <p>
            <code>content</code> is required. <code>user_id</code>, when provided, must be a UUID.
          </p>
        </div>
      </section>

      <section className="section">
        <h2>OpenAPI and Source Links</h2>
        <div className="grid">
          <a className="card" href={DOCS_SITE.tenantSwaggerUrl} target="_blank" rel="noopener noreferrer">
            <h3>Tenant Swagger UI</h3>
            <p>Open generated OpenAPI docs from the tenant service.</p>
          </a>
          <a className="card" href={DOCS_LINKS.gatewayReadme} target="_blank" rel="noopener noreferrer">
            <h3>Gateway API in OSS README</h3>
            <p>Primary endpoint reference and role requirements.</p>
          </a>
          <a className="card" href={DOCS_LINKS.mcpApiMapping} target="_blank" rel="noopener noreferrer">
            <h3>MCP to REST Mapping</h3>
            <p>Detailed API mapping between MCP tools and HTTP endpoints.</p>
          </a>
        </div>
        <div className="docActions">
          <Link href="/library/" className="btn btnPrimary">
            Browse Full Documentation Library
          </Link>
        </div>
      </section>
    </>
  );
}
